/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-16 16:57:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cdac.dto.User;
import com.cdac.dto.User;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Cache-Control.jsp", Long.valueOf(1692100544167L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1692100544950L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cdac.dto.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    ");

	response.setHeader("Cache-Control", "No-Store");
	response.setHeader("Cache-Control", "No-Cache");

      out.write("\n");
      out.write("    ");
      com.cdac.dto.User user = null;
      synchronized (session) {
        user = (com.cdac.dto.User) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (user == null){
          user = new com.cdac.dto.User();
          _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
 
	if(user !=null && user.getUserId()>0){

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Home Page</title>\n");
      out.write("<style >\n");
      out.write("	.a{\n");
      out.write("	opacity: 0.7;\n");
      out.write("     background: black;\n");
      out.write("	color: red;\n");
      out.write("	box-shadow: 10px 10px 5px black;\n");
      out.write("	}\n");
      out.write("	.a:hover {\n");
      out.write("	opacity: 1.0;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("h3 {\n");
      out.write("  \n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-image: url('30.jpeg');\n");
      out.write(" background-size:cover;\n");
      out.write(" background-position:center; \n");
      out.write(" background-repeat:no-repeat; \n");
      out.write(" background-origin: content-box;\n");
      out.write(" background-attachment: fixed;\n");
      out.write("  \n");
      out.write(" \">\n");
      out.write("   \n");
      out.write("      ");
      out.write("\n");
      out.write("  \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("ul {\n");
      out.write("  list-style-type: none;\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("  overflow: hidden;\n");
      out.write("  background-color: #333;\n");
      out.write("  border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("  float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a {\n");
      out.write("  display: block;\n");
      out.write("  color: white;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 14px 16px;\n");
      out.write("  text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover:not(.active) {\n");
      out.write("\n");
      out.write("  background-color: #111;\n");
      out.write("   border-radius: 10px;\n");
      out.write(" }\n");
      out.write("\n");
      out.write(".active {\n");
      out.write("  background-color: #4CAF50;\n");
      out.write("  border-radius: 6px;\n");
      out.write("  margin-top: 3px;\n");
      out.write("}\n");
      out.write("h3{\n");
      out.write("   font-size: 28px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Header Page</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  \n");
      out.write(" <ul>\n");
      out.write("  <li style=\"color: white; margin-right: 25px;margin-left: 25px;\"><h1>Easy Pay</h1></li>\n");
      out.write("  \n");
      out.write("  <li><h3 style=\"color: white;float:right;\"> Welcome ");
      out.print((session.getAttribute("user")!=null) ?((User)session.getAttribute("user")).getUserName():"   " );
      out.write(" !!!</h3></li>\n");
      out.write("  <li style=\"float:right\"><h3><a style=\"font-size: 28px;\"class=\"active\" href=\"logout.htm\">Logout</a></h3></li>\n");
      out.write("  <li style=\"float:right\"><h3><a style=\"font-size: 28px;\" href=\"prep_recharge_add_form.htm\">Recharge</a></h3></li>\n");
      out.write("  <li style=\"float:right\"><h3><a style=\"font-size: 28px;\" href=\"view_offer.htm\">Offers</a></h3></li>\n");
      out.write("  \n");
      out.write("</ul>\n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<!--<h1> Welcome ");
      out.print((session.getAttribute("user")!=null) ?((User)session.getAttribute("user")).getUserName():"!!!!!!!!" );
      out.write("</h1>-->\n");
      out.write("\n");
      out.write("	\n");
      out.write("   <div style=\"display:flex; justify-content:end; align-item:end ;margin-top:200px \" >\n");
      out.write("    	\n");
      out.write("      		<div class=\"a\" style=\"text-align: center; border; border-radius: 15% 50%; background:#c9ffe5 ;height: 130px; width: 130px;margin-left:220px\">\n");
      out.write("       		<br><a href=\"prep_recharge_add_form.htm\">\n");
      out.write("       		<h3 style=\"color:black;\">Recharge</a><br>\n");
      out.write("      		</div>\n");
      out.write("   		\n");
      out.write("   		\n");
      out.write("      		<div class=\"a\" style=\"text-align: center; border; border-radius: 15% 50%; background:#c9ffe5;height: 130px; width: 130px;margin-left:100px\">\n");
      out.write("  		 	<a href=\"recharge_Bill.htm\">\n");
      out.write("  		 	<h3 style=\"color:black;\">\n");
      out.write("  		 	See your Bills</a>\n");
      out.write("    		</div>\n");
      out.write("    	\n");
      out.write("   \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
 }else{
	
	response.sendRedirect("login_form.jsp");	
	
}
	
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
