/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-29 07:38:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("		\n");
      out.write("	");
      out.write("\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		");
      out.write("	\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Mobile Recharge App</title>\n");
      out.write("    <style>\n");
      out.write("       body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background-image: url('100.jpg'); /* Replace with your image's path or URL */\n");
      out.write("            background-size: cover; /* Adjust to your preference */\n");
      out.write("            background-position: center; /* Adjust to your preference */\n");
      out.write("         \n");
      out.write("        }\n");
      out.write("\n");
      out.write("	\n");
      out.write("        .container {\n");
      out.write("            max-width: 400px;\n");
      out.write("            margin: 60px auto; /* Adjust margin for centering */\n");
      out.write("            padding: 20px;\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8); /* Added a semi-transparent white background */\n");
      out.write("            border: 1px solid #e2e2e2;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("\n");
      out.write("        h1 {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            color: #007bff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        form {\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label, input {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"number\"],\n");
      out.write("        input[type=\"text\"] {\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            background-color: #007bff;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            width: 100%;\n");
      out.write("            transition: background-color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:hover {\n");
      out.write("            background-color: #0056b3;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #paymentStatus {\n");
      out.write("            margin-top: 20px;\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 18px;\n");
      out.write("            color: #007bff;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>Mobile Recharge App</h1>\n");
      out.write("        <form id=\"paymentForm\" action=\"/recharge\" method=\"post\">\n");
      out.write("            <label for=\"amount\">Recharge Amount:</label>\n");
      out.write("            <input type=\"number\" id=\"amount\" name=\"amount\" required>\n");
      out.write("            <label for=\"cardNumber\">Card Number:</label>\n");
      out.write("            <input type=\"text\" id=\"cardNumber\" name=\"cardNumber\" required>\n");
      out.write("            <label for=\"expiry\">Expiry Date:</label>\n");
      out.write("            <input type=\"text\" id=\"expiry\" name=\"expiry\" placeholder=\"MM/YY\" required>\n");
      out.write("            <label for=\"cvv\">CVV:</label>\n");
      out.write("            <input type=\"text\" id=\"cvv\" name=\"cvv\" required>\n");
      out.write("            <button type=\"submit\" id=\"payNowButton\">Pay Now</button>\n");
      out.write("        </form>\n");
      out.write("        <div id=\"paymentStatus\"></div>\n");
      out.write("    </div>\n");
      out.write("    <script>\n");
      out.write("        document.getElementById('paymentForm').addEventListener('submit', function(event) {\n");
      out.write("            event.preventDefault(); // Prevent the default form submission\n");
      out.write("            \n");
      out.write("            // Redirect to Success1.jsp\n");
      out.write("            window.location.href = 'Success1.jsp';\n");
      out.write("            \n");
      out.write("            // You can also perform other actions here, like showing a loading spinner\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("			\n");
      out.write("	\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("\n");
      out.write("		\n");
      out.write("			\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
